### ISSUE TITLE
Please help me setup blabel. 

### ISSUE THREAD

**Issue by aidenmj** [Edinburgh-Genome-Foundry/blabel#11]
I tried 2 ways from Visual Studio (still a rookie) & Ananconda Prompt, conda can't install blabel. 
My goal is to scan a barcode(ID) and it's look up other columns, names and others details will be printed along with barcode of ID.
Thanks in advance. I just need to setup and able to run the test script is enough.

**Comment by veghp** [comment]
What was the issue? In your terminal prompt you can install blabel with `pip install blabel`, preferably in your anaconda environment. It's not packaged as a conda package.
Using blabel requires knowledge of Python, HTML and CSS.
As for running a test issue the command: `python testscript.py` or the code itself in a Python prompt.

**Comment by aidenmj** [comment]
Hi, thank you for reaching out. I managed to install blabel via setup.py install. I'm still going through the codes, is there way to remove the text under the barcode(it's value). 
![image](https://user-images.githubusercontent.com/37358382/111710913-98c4e300-8885-11eb-9287-5a262b52d48c.png)
and is there way to add in auto printing on script run for windows.

**Comment by veghp** [comment]
Removing text: blabel uses [python-barcode](https://python-barcode.readthedocs.io/en/stable/). When you call [`label_tools.barcode()`](https://edinburgh-genome-foundry.github.io/blabel/ref.html?highlight=barcode#blabel.label_tools.barcode), simply pass the `writer_options`. See [Writer options documentation](https://python-barcode.readthedocs.io/en/stable/writers/index.html). Perhaps setting text size to `0` solves this. [For example](https://github.com/Edinburgh-Genome-Foundry/blabel/blob/master/examples/barcode_and_dynamic_picture/item_template.html
): 
`label_tools.barcode(sample_id, module_width=1.5, font_size=0)`

Can you please clarify your second question? (auto printing)

**Comment by aidenmj** [comment]
My program flow would be, when the person scan his/her badge barcode, the input will lookup for name and other 2 columns and generate the barcode and the other information, then it should print it. Only trigger is the barcode input. Entry if not blank, run function to generate and print then return. Following person will be scanning their badge to print the barcode. Please share if you anything to share that might be helpful for my program.

Additional information.
I am doing this program in tkinter(GUI) python program. I wanted to use an excel sheet as data source for lookup. and this program later on will be executable in more than one pc. 
Thank you.

**Comment by veghp** [comment]
Thanks for explaining, sounds like an interesting project. Nothing particular comes to mind regarding this. Please consider sharing the code once your project is finished.

**Comment by aidenmj** [comment]
Hi I've managed to compiled all the function in a script. With Barcode Scanner input it will look up for the record from database and barcode will be generated into pdf files. Then cmd script will run the printing process (uses Acrobat) & that Arcobat will be terminated. All the process will be trigger with only one Barcode Scanner input. After done printed, the next user can scan their badge for printing the sticker label. 

Issues I'm having now, I wanted to make the whole py script into .EXE. Can **blabel** script can be executable? I managed to add .db file for the database. Other files such .html and .css files for the barcode pdf templates, I tried to include multiple files, But I can't manages to run it. 

Any tips and guide in command for pyinstaller would be great. thanks
This is my files need to run the script. 
![image](https://user-images.githubusercontent.com/37358382/113099986-5f995500-922d-11eb-9767-2a20bdef8ec6.png)

**Comment by veghp** [comment]
Thanks for the details. Well, normally you would execute the script with `python LabelPrint.py`. Unfortunately I cannot further advise you on building an .exe program. This is a general programming question not specific to blabel. I'll close this as the original 'text under the barcode' issue has been solved.

**Comment by aidenmj** [comment]
Thank you!
