### ISSUE TITLE
How to print multiple stickers in one row.

### ISSUE THREAD

**Issue by healperci** [Edinburgh-Genome-Foundry/blabel#15]
Hi there!!!

I'm triying to generate a pdf with 3 stickers per row for a zebra printer, ¿is this posible with this library?

[this is the paper ](
https://articulo.mercadolibre.com.co/MCO-495824978-etiquetas-adhesivas-para-impresoras-sato-goodex-tsc-zebra-_JM?matt_tool=31045937&matt_word=&matt_source=google&matt_campaign_id=14633851806&matt_ad_group_id=135195454464&matt_match_type=&matt_network=g&matt_device=c&matt_creative=552892033103&matt_keyword=&matt_ad_position=&matt_ad_type=pla&matt_merchant_id=270068328&matt_product_id=MCO495824978&matt_product_partition_id=1437621058765&matt_target_id=aud-345731277302:pla-1437621058765&gclid=Cj0KCQjwrJOMBhCZARIsAGEd4VH2bGm4oT22yTcNI6pYTpBuO8cTLV_hpLIxdVwhFoB652J0bG9ko0MaArilEALw_wcB)

Thanks in advance.

**Comment by veghp** [comment]
Hi, thanks for your interest in this package -- I suspect this issue can be solved with the printer, not with this software. The printer you posted still has individual stickers ('pages') in each row. Here is a step-by-step description on creating labels with two or more columns: https://www.zebra.com/us/en/support-downloads/knowledge-articles/evm/How-to-create-labels-with-two-or-more-columns-on-Zebra-Designer-V3.html

Does this help?

**Comment by healperci** [comment]
Hi, Jaguar YOu?? no I'm a tiger!!! (colombian joke, for spanglish speakers like me)

I solved through there, build the Python application, then point to Zebra software, was easy and a quality product, Thanks for the answer!!!
