### ISSUE TITLE
QR Code is too small to scan with web cam

### ISSUE THREAD

**Issue by rickmedlin** [Edinburgh-Genome-Foundry/blabel#16]
On the whole, this is an amazing package and creates labels in just the size and format that I need.

My one stumbling block is that the I can scan the QR codes that it creates with my phone camera, but not with the web cam on my PC. Has anyone else mentioned that or found a way to handle it?

**Comment by Zulko** [comment]
Hmm that's weird. Maybe the software you are using on your PC doesn't recognize this particular format of QR code? For what it's worth I remember testing this with a PC webcam.

**Comment by rickmedlin** [comment]
Maybe.  I'm running Windows 10, Python 3.10 with a Logicam C310 camera.  Very inexpensive camera with fixed focus.

**Comment by rickmedlin** [comment]
As it happens we will be buying scanners.  Closing this for now.
