### ISSUE TITLE
Putting multiple elements into QR code

### ISSUE THREAD

**Issue by rickmedlin** [Edinburgh-Genome-Foundry/blabel#17]
The more I use this package, the more I like it.  However I would like to put multiple elements in the QR code.

I've tried these ways without success in the Jinja / image template:

```<img src="{{label_tools.qr_code(element_1, element_2, element_3)}}" />```

```<img src="{{label_tools.qr_code(element_1)}} {{label_tools.qr_code(element_2)}} {{label_tools.qr_code(element_3)}}" />```

Is this possible?

**Comment by rickmedlin** [comment]
Adding a screen shot because my code did not come through in the previous comment.

![qr](https://user-images.githubusercontent.com/49470274/146597646-3ec3e2f9-1e9d-46aa-ad5a-5ad537020a5e.jpg)

**Comment by rickmedlin** [comment]
Never mind,  A little research showed that one solution is the ~ operator:

```<img src="{{label_tools.qr_code(element_1 ~ element_2 ~ element_3)}}" />```

**Comment by Zulko** [comment]
Oh wow that sounds fancy, can you explain what it does?

**Comment by rickmedlin** [comment]
Not really fancy. As shown above, if you want to join multiple values inside a 'qr_code' statement, concatenate them with a '~'.

**Comment by veghp** [comment]
I leave this here for future reference: https://jinja.palletsprojects.com/en/3.0.x/templates/#other-operators
```
~ (tilde)
    Converts all operands into strings and concatenates them.
    {{ "Hello " ~ name ~ "!" }} would return (assuming name is set to 'John') Hello John!.
```
