### ISSUE TITLE
Don't force an specific weasyprint version

### ISSUE THREAD

**Issue by bellini666** [Edinburgh-Genome-Foundry/blabel#19]
Hi,

The last version of this lib started to force weasyprint <= 52 due to the fact that `not all GNU/Linux distributions have the latest Pango that is required by the latest WeasyPrint`.

Although the reasoning is understandable, I think it is too much for blabel to force that, making it impossible for an app that _can_ run weasyprint >= 53 and requires a newer version to use this lib.

I would suggest adding a note on `README` that if someone have issues with pango, they should fix their weasyprint installation to <=52 and loose this lib's requirement again.

**Comment by veghp** [comment]
hi, thanks, yes that's a valid request. Will look into it tomorrow.

**Comment by bellini666** [comment]
Thank you! :)
