### ISSUE TITLE
module 'barcode' has no attribute 'get_barcode_class'

### ISSUE THREAD

**Issue by gaetanbarras** [Edinburgh-Genome-Foundry/blabel#22]
Hello,

I can't use blabel with barcode.
with Qr code it's work fine but when i use "`<img src="{{label_tools.barcode(sample_id, module_width=1, font_size=50)}}"/>`" in my template i have this issue (module 'barcode' has no attribute 'get_barcode_class')

I reinstall with pip install python-barcode but nothing to do, same issue.

python version 3.9.2
django version 3.1.3

**Comment by veghp** [comment]
The functionality works for me. See simplified example from tests below. The only difference I can see is the missing `class='barcode'` in (`item_template.html`): `<img class='barcode' src='{{label_tools.barcode(sample_id, module_width=1.5, font_size=30)}}' />`

```python
import os
import blabel

def get_template_and_style(folder_name):
    folder = os.path.join(folder_name)
    template = os.path.join(folder, "item_template.html")
    style = os.path.join(folder, "style.css")
    return template, style

template, style = get_template_and_style("barcode_and_dynamic_picture")
label_writer = blabel.LabelWriter(
    template, default_stylesheets=(style,), 
    # generate_identicon=generate_identicon,
)
records = [
    dict(sample_id="s01", sample_name="Sample 1"),
    dict(sample_id="s02", sample_name="Sample 2"),
    dict(sample_id="s03", sample_name="Sample 3"),
]

label_writer.write_labels(records, target="test_barcode.pdf")
```
[test_barcode.pdf](https://github.com/Edinburgh-Genome-Foundry/blabel/files/9598744/test_barcode.pdf)


Versions:
```bash
blabel                        0.1.6
python-barcode                0.13.1
WeasyPrint                    52
Jinja2                        3.1.2
```

**Comment by gaetanbarras** [comment]
Merci,

I found the error, I installed the python-barcode and barcode library and that creat conflict.

thank you
