### ISSUE TITLE
Cairo library module not loading

### ISSUE THREAD

**Issue by RobbieS82** [Edinburgh-Genome-Foundry/blabel#8]
![missing_module](https://user-images.githubusercontent.com/71034808/104799386-5848da80-57ec-11eb-8e75-4950cbd2578e.png)

I get this after running the pip install on Windows 10 console (in administrator mode), and then trying to run the example code provided.  Errors seem to indicate dependent libraries are not loading

**Comment by veghp** [comment]
Thanks for reporting this. EGF packages were developed and tested on Ubuntu (GNU/Linux) with Python 3.6.7. We will add a notice to the documentation about this, in the future. I installed blabel now into a new conda environment to test it, and it works well. Unfortunately, Windows is not supported. In most cases the packages work without problems on other OSs, but not always.
Not sure where your instance was installed, but it is not recommended to use the operating system's Python. A better way is to create an environment (e.g. with [Anaconda](https://www.anaconda.com/products/individual)), and install into that. This _may_ solve the problem according to [this answer](https://stackoverflow.com/a/63946744).

**Comment by bbrendon** [comment]
Its working for me on debian 10 with venv.

**Comment by cammo1234** [comment]
Hi all, @RobbieS82 @veghp 

### Here is how to get Blabel to work on Windows 10.
One of Blabel's dependencies is a Python package called [WeasyPrint](https://pypi.org/project/weasyprint/).  WeasyPrint is automatically installed as a dependency when you run `pip install Blabel`. 

On Windows, WeasyPrint will not function without the installation of some additional libraries from GTK+. Cairo is one of these libraries. Please closely follow the official WeasyPrint [instructions here](https://weasyprint.readthedocs.io/en/stable/install.html). These instructions will step you through the process, and they contain working links to the required libraries.

I was able to get Blabel and WeasyPrint to work on my Windows 10 x64 machine.

**Comment by veghp** [comment]
Thank you very much for the description and confirmation of this.
